### ISSUE TITLE
Finish event not working

### ISSUE THREAD

**Issue by TaimurTTS** [kottenator/jquery-circle-progress#180] opened 2018-02-09 14:49 UTC
Hi there,
I'm trying to fire trigger on finish event. but it is not working if user switch tab. If user change tab finish event doesn't work until user comeback again to that tab

**Comment by kottenator** [comment] 2018-03-03 21:05
I know, that's a problem. But that's an existing problem (which I still didn't have a chance to fix). So I'm closing this ticket as a duplicate of #166.

**Closed as completed by kottenator** 2018-03-03 21:05 UTC
Labels: duplicate
