### ISSUE TITLE
extra stepValue in circle-animation-progress

### ISSUE THREAD

**Issue by tatol** [kottenator/jquery-circle-progress#141] opened 2017-04-17 09:05 UTC
Hello! I use Mithril 1.1.1 and use 2 objects with circleProgress. In first object i use circle-animation-progress event. And circle-animation-progress event use final stepValue from second circleProgress value. Could you check this ? I fix this by checking event target className.

**Comment by kottenator** [comment] 2017-04-17 11:30
Hi, @tatol! Could you, please, provide a jsbin?

**Comment by tatol** [comment] 2017-04-17 14:04
[link](https://jsfiddle.net/14e6oauj/4/) . There should be 0.2, but it out 0.8.

**Comment by kottenator** [comment] 2017-04-17 14:15
Thanks! Here's the problem: you have two circle containers, one inside another:

* `tabs__tab-content__content-body__diagramm` (**circle 1**)
** `.tabs__tab-content__content-body__diagramm__white-part` (**circle 2**)

You've subscribed to `circle-animation-progress` event of the **circle 1** _but_ due to current implementation, the event is _propagated_ from the child circle up to `body`, so you've actually subscribed to `circle-animation-progress` event of the **circle 1** _and_ **circle 2** at the same time.

I know, that's weird, and most likely I'll change this in the future.

But for now, to fox the problem, you can do the following:

```js
$(".tabs__tab-content__content-body__diagramm").circleProgress({
  // circle 1 options
}).on("circle-animation-progress", function(event, progress, stepValue) {
  // use stepValue
});

$(".tabs__tab-content__content-body__diagramm__white-part").circleProgress({
  // circle 2 options
}).on("circle-animation-progress", function(event, progress, stepValue) {
  event.stopPropagation();  // this line should help
});
```

Or you can separate these two circles into _sibling_ elements instead of _parent / child_.

**Comment by tatol** [comment] 2017-04-17 16:15
Thank you! Now I understand why this is happening

**Comment by kottenator** [comment] 2017-04-17 16:17
No problem! I guess the problem is solved now? I'm closing the ticket.

P.S.: the same issue has appeared before - #68.

**Closed by kottenator** 2017-04-17 16:17 UTC
Labels: help wanted
