### ISSUE TITLE
animationStartValue should be last value when changing colors

### ISSUE THREAD

**Issue by dresende** [kottenator/jquery-circle-progress#91] opened 2016-05-03 10:44 UTC
When you set a new value, the animation goes from last value to the new one. If you change the value and also the colors (or just the colors), the animation goes from zero.

Example:

```js
$("#progress").circleProgress({
    value     : .5,
    fill      : { color: "#a00" }
});

setTimeout(function () {
    $("#progress").circleProgress({
        value     : .8,
        fill      : { color: "#0a0" }
    });
}, 2000);
```

Instead of changing color (from red to green) and going from 50% to 80%, it goes from 0% to 80%.

As a workaround:

```js
setTimeout(function () {
    $("#progress").circleProgress({
        value               : .8,
        fill                : { color: "#0a0" },
        animationStartValue : $("#progress").circleProgress("value")
    });
}, 2000);
```

**Comment by kottenator** [comment] 2016-05-03 12:08
Yes, you are correct, that's how it's designed now, is not a big. And the workaround is correct. You can also do the same via:

```js
$("#progress").circleProgress({
    value: .5,
    fill: { color: "#a00" }
});

setTimeout(function () {
    $("#progress").circleProgress({
        fill: { color: "#0a0" }
    }).circleProgress('value', .8);
}, 2000);
```

**Comment by kottenator** [comment] 2016-05-05 21:15
Feel free to reopen this ticket, but I'm closing it for now because it's "as designed", not a bug

**Closed** 2016-05-05 21:14 UTC
Labels: enhancement, wontfix
