### ISSUE TITLE
Support for Multiple Segments

### ISSUE THREAD

**Issue by clemsontiger** [kottenator/jquery-circle-progress#82] opened 2016-03-17 17:39 UTC
Does it support multiple segments, or is there a way to achieve this? i.e. one segment one color and a second segment around the same circle, starting where the first segment stopped. 

see sample image:  http://drp.mk/i/0qKMVrGF7d

thanks.

**Comment by kottenator** [comment] 2016-03-21 21:26
Please, take a look at #56

**Comment by kottenator** [comment] 2016-03-24 16:49
I hope the problem is solved. I'm closing this ticket

**Closed by kottenator** 2016-03-24 16:49 UTC
Labels: help wanted

**Comment by clemsontiger** [comment] 2016-03-24 17:15
Sorry, yes, was still working on my code this morning using the snippet in #56  you provided.  Not exactly what I needed in terms of how it works (instead of stacking the sectors I was hoping they would flow one after the other), but I think it'll do. much appreciated!
